# SAM Configuration for CI/CD Deployments

version = 0.1

[default]
[default.global.parameters]
stack_name = "automated-video-pipeline"
s3_bucket = "automated-video-pipeline-deployments"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "automated-video-pipeline"
s3_bucket = "automated-video-pipeline-deployments"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
parameter_overrides = "Environment=dev"

[default.package.parameters]
s3_bucket = "automated-video-pipeline-deployments"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development Environment
[dev]
[dev.deploy.parameters]
stack_name = "automated-video-pipeline-dev"
s3_bucket = "automated-video-pipeline-deployments-dev"
parameter_overrides = "Environment=dev"

# Staging Environment  
[staging]
[staging.deploy.parameters]
stack_name = "automated-video-pipeline-staging"
s3_bucket = "automated-video-pipeline-deployments-staging"
parameter_overrides = "Environment=staging"

# Production Environment
[prod]
[prod.deploy.parameters]
stack_name = "automated-video-pipeline-prod"
s3_bucket = "automated-video-pipeline-deployments-prod"
parameter_overrides = "Environment=prod"