# SAM Configuration for Multi-Environment Deployment

version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "automated-video-pipeline"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "automated-video-pipeline-dev"
s3_bucket = "automated-video-pipeline-deployments-dev"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
parameter_overrides = "Environment=dev"

[default.package]
[default.package.parameters]
s3_bucket = "automated-video-pipeline-deployments-dev"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development Environment
[dev]
[dev.global]
[dev.global.parameters]
stack_name = "automated-video-pipeline-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[dev.deploy]
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "automated-video-pipeline-dev"
s3_bucket = "automated-video-pipeline-deployments-dev"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
parameter_overrides = "Environment=dev"

[dev.package]
[dev.package.parameters]
s3_bucket = "automated-video-pipeline-deployments-dev"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"

# Staging Environment
[staging]
[staging.global]
[staging.global.parameters]
stack_name = "automated-video-pipeline-staging"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"

[staging.deploy]
[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "automated-video-pipeline-staging"
s3_bucket = "automated-video-pipeline-deployments-staging"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
parameter_overrides = "Environment=staging"

[staging.package]
[staging.package.parameters]
s3_bucket = "automated-video-pipeline-deployments-staging"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"

# Production Environment
[prod]
[prod.global]
[prod.global.parameters]
stack_name = "automated-video-pipeline-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"

[prod.deploy]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "automated-video-pipeline-prod"
s3_bucket = "automated-video-pipeline-deployments-prod"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
parameter_overrides = "Environment=prod"

[prod.package]
[prod.package.parameters]
s3_bucket = "automated-video-pipeline-deployments-prod"
s3_prefix = "automated-video-pipeline"
region = "us-east-1"
